server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # Configuracao opcional, do endereco da instancia do Eureka
spring:
  application:
    name: cambio-service
  datasource: # Configuracao do banco de dados
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Nao utilizar em ambientes de producao, dev e etc, pois diminui a performance
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway: # Responsavel por organizar os scripts que sao executados no banco de dados
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin123
  sleuth:
    sampler:
      probability: 1.0 # Configuracao do percentual que deve ser feito log pelo Sleuth, 1.0 equivale a 100%, o ideal em ambientes de producao e de 0.05, 5%
  #zipkin:
    #base-url: http://localhost:9411 # Por padrao, o zipkin ja tem a porta 9411 configurada, se quisermos alterar, temos que usar essa propriedade
springdoc:
  show-actuator: true
  api-docs: # Configuracao para o Gateway conseguir captar o Swagger desse servico
    path: cambio-service/v3/api-docs # Caminho do servico apos o load balancer(sem ter o 'cambio-service' replicado no path)