version: '3.4'
# A propriedades do docker-compose sobrescrevem as do application.yml
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - erudio-network # Rede definida em que os servicos devem se conectar

  cambio-db: # Configuracao DB
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password # Comando executado assim que o container inicializar, senha nativa
    restart: always # Se ocorrer uma falha, sera reiniciado
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service # DB que sera criada automaticamente
      MYSQL_ROOT_HOST: '%' # Configuracao para permitir hosts diferentes
      MYSQL_TCP_PORT: 3308 # Configuracao para forcar o uso da porta 3308
    ports:
      - 3308:3308
    expose:
      - 3308 # Configuracao para expor na porta 3308

  book-db: # Configuracao DB
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password # Comando executado assim que o container inicializar, senha nativa
    restart: always # Se ocorrer uma falha, sera reiniciado
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service # DB que sera criada automaticamente
      MYSQL_ROOT_HOST: '%' # Configuracao para permitir hosts diferentes
      MYSQL_TCP_PORT: 3310 # Configuracao para forcar o uso da porta 3308
    ports:
      - 3310:3310
    expose:
      - 3310 # Configuracao para expor na porta 3308

  naming-server:
    image: sussusallum/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      -  erudio-network # Rede definida em que os servicos devem se conectar

  api-gateway:
    image: sussusallum/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEAULTZONE: http://naming-server:8761/eureka # Configuracao do Eureka passando o nome do servico, nesse caso naming-server
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # Configuracao para o api-gateway se conectar ao Zipkin, passando o nome do servico
    networks:
      - erudio-network # Rede definida em que os servicos devem se conectar

  cambio-service: # Configuracao DB
    image: sussusallum/cambio-service
    restart: always # Se ocorrer uma falha, sera reiniciado
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEAULTZONE: http://naming-server:8761/eureka # Configuracao do Eureka passando o nome do servico, nesse caso naming-server
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/ # Configuracao para o api-gateway se conectar ao Zipkin, passando o nome do servico
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8000:8000
    depends_on: # Cambio-service precisa dos dois servicos abaixo para funcionar
      - naming-server
      - cambio-db

networks:
  erudio-network:
    driver: bridge